sudo: required
language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - docker build -t docker-react-test -f Dockerfile.test .

script:
  - docker run docker-react-test npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerReact"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-151245278723"
  bucket_path: "DockerReact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
