sudo: required
language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - docker build -t docker-react-test -f Dockerfile.test .

script:
  - docker run docker-react-test npm run test -- --watchAll=false
